### PR TITLE
Insulate against RayCast fail

### LINKED ISSUE #97: Shotgun raycast not insulated against situations where nothing is hit

### PR DESCRIPTION
**Pull request by ninyauwu**
Closes #97
### Summary
Insulate against situations where shotgun raycasts fail to hit anything.

### 1. Merging
- [x] Did you select the dev branch?
### 2. File Structure
- [x] Are all scripts placed within Assets/Scripts and organized into logical categories using PascalCase (e.g., Core, Player, Level)?
- [x] Are assets like materials, textures and sound files named using lower_snake_case (e.g., diamond_pickaxe.png)?
- [x] Did the changes avoid unnecessary scene modifications? If new changes were needed for testing, were they done in Scenes/Dev/<Specification> and then discarded?
### 3. Code
- [x] Do private fields start with an underscore and use camelCase (e.g., _privateVariable)?
- [x] Are static readonly variables named using UPPER_SNAKE_CASE?
- [x] Are enum types also in UPPER_SNAKE_CASE?
- [x] Are function and variable names clear, concise, and descriptive without using unnecessary abbreviations?
- [x] Are all public functions and fields documented with clear summaries where needed
- [x] Does the code maintain a strict hierarchy, ensuring objects do not fetch references themselves or their parents in the hierarchy?
- [x] Are references passed down through dependency injection as needed?Does each component only depend on its parent in the hierarchy?
- [x] Have unnecessary/testing Debug.Logs been removed?
- [x] Has commented code been removed?
### 4. Logging
- [ ] If possible, did you make a video and did you send it/a link to it in the feature-videos channel?

### CODE REVIEW

**Review by TheBulletBot — APPROVED** [review]

File: Project/Assets/Scripts/Weapons/Weapon.cs [hunk 1]
```diff
@@ -186,13 +188,14 @@ public void DoHitReg(Transform bulletOriginPoint, Camera camera, RectTransform c
...
         {
-            Debug.LogError("Unknown Spread Type. No spread will be added");
+            Debug.LogWarning("Unknown Spread Type. No spread will be added");
             spreadPattern = NoSpreadPattern(bulletOriginPoint.position, gunTarget);
         }
         var hits = DeterminePelletHits(spreadPattern, bulletOriginPoint);
 
         foreach (var target in hits)
         {
+            if (target.collider == null) continue;
```
Comment (IcyKoala) [inline Project/Assets/Scripts/Weapons/Weapon.cs:198]: Not sure what the point of this check is as it seems pointless?
A raycast needs a collider to hit, so by default there is always a collider?

File: Project/Assets/Scripts/Weapons/Weapon.cs [hunk 2]
```diff
@@ -49,7 +49,9 @@ public Vector3 CrosshairToGunTarget(Camera camera, RectTransform crosshair)
         {
             return hit.point;
         }
-        return ray.direction;
+
+        // If nothing was hit, return a point at a fixed faraway distance
+        return (ray.direction * 1000.0F) + bulletOriginPoint;
```
Comment (IcyKoala) [inline Project/Assets/Scripts/Weapons/Weapon.cs:54]: Not sure what the point off adding the bulletOriginPoint here is? feels like unnecessary extra passed data, but not sure on that one

**Review by IcyKoala — CHANGES_REQUESTED** [review]
2 minor performance points/questions

File: Project/Assets/Scripts/Weapons/Weapon.cs (hunk 1 above)
Comment (ninyauwu) [reply Project/Assets/Scripts/Weapons/Weapon.cs:198]: Actually no. Counterintuitively, a RaycastHit object is not necessarily a hit. It's just the name of the information container that's returned by a Raycast, even if the Raycast doesn't hit anything. You can here about RaycastHit.colldier here:
https://docs.unity3d.com/530/Documentation/ScriptReference/RaycastHit-collider.html

**Review by IcyKoala — APPROVED** [review]
